//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialManager.DataEntities.CredentialStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CredentialManagerStoreEntities : DbContext
    {
        public CredentialManagerStoreEntities()
            : base("name=CredentialManagerStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CredentialStore> CredentialStore { get; set; }
        public virtual DbSet<CredentialTypes> CredentialTypes { get; set; }
        public virtual DbSet<AuthenticationProtocol> AuthenticationProtocol { get; set; }
        public virtual DbSet<PrivacyProtocol> PrivacyProtocol { get; set; }
        public virtual DbSet<ServiceUsers> ServiceUsers { get; set; }
        public virtual DbSet<CredentialRole> CredentialRole { get; set; }
        public virtual DbSet<Principals> Principals { get; set; }
        public virtual DbSet<UserCredentials> UserCredentials { get; set; }
        public virtual DbSet<LoginAttempts> LoginAttempts { get; set; }
    }
}
