//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialManager.DataEntities.CredentialStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredentialStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CredentialStore()
        {
            this.UserCredentials = new HashSet<UserCredentials>();
        }
    
        public System.Guid Id { get; set; }
        public string CredentialKey { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SecurityStamp { get; set; }
        public string CredentialType { get; set; }
        public string SSHphassphrase { get; set; }
        public string SSHprivatekey { get; set; }
        public string AuthenticationProtocol { get; set; }
        public string PrivacyProtocol { get; set; }
        public DateTime? CreateTime { get; set; } = DateTime.Now;
        public DateTime? LastChange { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCredentials> UserCredentials { get; set; }
    }
}
