//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialManager.DataEntities.CredentialStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempts
    {
        public System.Guid Id { get; set; }
        public System.Guid PrincipalId { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<System.DateTime> LockedTime { get; set; }
    
        public virtual Principals Principals { get; set; }
    }
}
