//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialManager.DataEntities.CredentialStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Principals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Principals()
        {
            this.LoginAttempts = new HashSet<LoginAttempts>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public System.Guid RoleId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual CredentialRole CredentialRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginAttempts> LoginAttempts { get; set; }
    }
}
